fix: set log level for snowflake
newrelic-experimental/newrelic-snowflake-integration pull request #70
Opened 2024-08-23 14:01 UTC by EdwOK

Hi Devs.

I've noticed that when I use your integration tools, Snowflake log messages are appearing in New Relic events, which seems to be breaking their schema. The logs look something like this:

![image](https://github.com/user-attachments/assets/d3787e0d-4d7e-4e15-abec-5e3f5fb74bc8)

I suggest adjusting the Snowflake logging levels to resolve this issue.

2024-08-23 14:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic-experimental/newrelic-snowflake-integration?pullRequest=70) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic-experimental/newrelic-snowflake-integration?pullRequest=70) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic-experimental/newrelic-snowflake-integration?pullRequest=70) it.</sub>

2024-08-23 14:02 UTC, EdwOK commented
@danifitz @maju6406 @matewilk

2024-08-27 11:07 UTC, EdwOK commented
Hi @jbeveland27, please take a look

2025-02-04 17:15 UTC, sdewitt-newrelic commented
Hi @EdwOK can you help me understand what you mean by this?

> Snowflake log messages appear in NewRelic events, which seems to break their schema.

Also, I'd rather just set the `logLevel` property in the `config.yaml` to `ERROR` by default.  I didn't realize it was an empty value.  That's an omission.  Then we don't need any code to default it and if the user happens to choose something else, it's up to them to set it properly.  If we know setting it to some levels causes something like what you are saying, we can include it in the documentation.  But I'm not quite sure what you mean, hence my first question.

2025-02-04 17:38 UTC, EdwOK commented
> Also, I'd rather just set the `logLevel` property in the `config.yaml` to `ERROR` by default. I didn't realize it was an empty value. 

If it works

> Then we don't need any code to default it and if the user happens to choose something else, it's up to them to set it properly. If we know setting it to some levels causes something like what you are saying, we can include it in the documentation. But I'm not quite sure what you mean, hence my first question.

The main problem is that by default snowflake provider uses INFO for logs and this breaks expected output in JSON.

2025-02-06 17:00 UTC, sdewitt-newrelic commented
@EdwOK Thanks for responding.  I understand the issue now.  We really shouldn't be adding _anything_ to stdout at all other than our JSON since we are running as an infrastructure integration.  Even with the snowflake log level set to `ERROR`, we still could get output on standard error that would cause problems.  So even if we default it, there would be the potential for issues.  It seems like we either want to redirect it to stderr or turn it off altogether.

It looks like by default, the snowflake SDK always logs to [the file `snowflake.log`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L21).  The current problem is that it is also logging to the console by default.  Fortunately, there is an option called [`additionalLogToConsole`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L23C7-L23C29) that disables this behavior.  So since we can't redirect it to stderr and we already will have the logLevel in `snowflake.log` anyway, I suggest we simply disable the additional logging to console.  That said, it also would be nice to set the log level of the snowflake winston logger to whatever the user has specified for the integrations winston logger as well.  So perhaps we can simply do something like this.

```javascript
snowflake.configure({ logLevel: config.logLevel, additionalLogToConsole: false })
```

2025-05-01 21:18 UTC, brow86 commented
> It looks like by default, the snowflake SDK always logs to [the file `snowflake.log`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L21). The current problem is that it is also logging to the console by default. Fortunately, there is an option called [`additionalLogToConsole`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L23C7-L23C29) that disables this behavior. So since we can't redirect it to stderr and we already will have the logLevel in `snowflake.log` anyway, I suggest we simply disable the additional logging to console. That said, it also would be nice to set the log level of the snowflake winston logger to whatever the user has specified for the integrations winston logger as well. So perhaps we can simply do something like this.
> 
> ```js
> snowflake.configure({ logLevel: config.logLevel, additionalLogToConsole: false })
> ```

+1, this is it.  In short, the agent, as it stands now, produces a bunch of INFO lines when running the query that throw off the results forwarded to NewRelic.  For example, running manually in the container:
```
snowflake-linux -c config.yaml -q tenant_org_credit_usage.sql
{"level":"INFO","message":"[7:25:18.006 PM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[7:25:18.121 PM]: No client config file found in default directories"}
{"level":"INFO","message":"[7:25:18.122 PM]: Easy Logging is disabled as no config has been found"}
[{ < JSON RESULTS > }]
```
So to the earlier point, we'd need to update the PR to include that line above [here](https://bnym-eagle.slack.com/archives/CTM6KJJEM/p1746133957023349?thread_ts=1746133004.216259&cid=CTM6KJJEM)
```
snowflake.configure({ logLevel: config.logLevel, additionalLogToConsole: false })
```

2025-05-02 08:25 UTC, EdwOK commented
> > It looks like by default, the snowflake SDK always logs to [the file `snowflake.log`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L21). The current problem is that it is also logging to the console by default. Fortunately, there is an option called [`additionalLogToConsole`](https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/lib/logger/node.js#L23C7-L23C29) that disables this behavior. So since we can't redirect it to stderr and we already will have the logLevel in `snowflake.log` anyway, I suggest we simply disable the additional logging to console. That said, it also would be nice to set the log level of the snowflake winston logger to whatever the user has specified for the integrations winston logger as well. So perhaps we can simply do something like this.
> > ```js
> > snowflake.configure({ logLevel: config.logLevel, additionalLogToConsole: false })
> > ```
> 
> +1, this is it. In short, the agent, as it stands now, produces a bunch of INFO lines when running the query that throw off the results forwarded to NewRelic. For example, running manually in the container:
> 
> ```
> snowflake-linux -c config.yaml -q tenant_org_credit_usage.sql
> {"level":"INFO","message":"[7:25:18.006 PM]: Trying to initialize Easy Logging"}
> {"level":"INFO","message":"[7:25:18.121 PM]: No client config file found in default directories"}
> {"level":"INFO","message":"[7:25:18.122 PM]: Easy Logging is disabled as no config has been found"}
> [{ < JSON RESULTS > }]
> ```
> 
> So to the earlier point, we'd need to update the PR to include that line above [here](https://github.com/newrelic-experimental/newrelic-snowflake-integration/pull/70/files#diff-cef715b200e62b84973fb4ab65abb3035bf720d384d6482165cd2bfe7ba1b8b2R82)
> 
> ```
> snowflake.configure({ logLevel: config.logLevel, additionalLogToConsole: false })
> ```

Thanks for mention, updated.

2025-05-02 13:13 UTC, sdewitt-newrelic requested changes
@EdwOK I think I would prefer to see us default the `logLevel` in the config to `ERROR` and then just call `snowflake.configure(...)` without the need for the code to default using `setSnowflakeLogLevel`.

2025-05-02 14:28 UTC, EdwOK commented
> @EdwOK I think I would prefer to see us default the `logLevel` in the config to `ERROR` and then just call `snowflake.configure(...)` without the need for the code to default using `setSnowflakeLogLevel`.

Yeah, got you. Done.

2025-05-02 15:59 UTC, sdewitt-newrelic requested changes

2025-05-02 15:59 UTC, sdewitt-newrelic commented on snowflake.js
> +    snowflake.configure({ logLevel: 'ERROR', additionalLogToConsole: false })
The [winston log levels](https://github.com/winstonjs/winston?tab=readme-ov-file#using-logging-levels) and the [Snowflake SDK log levels](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-logs#supported-log-levels) overlap but there are a few differences.  Rather than hardcoding `ERROR` for the snowflake SDK log level, I think we need to convert from the Winston level to an appropriate Snowflake SDK level.

Maybe something like this.

| Winston | snowflake |
| --- | --- |
| (null) | OFF |
| error | ERROR |
| warn | WARNING |
| info | INFO |
| http | DEBUG |
| verbose | DEBUG |
| debug | DEBUG |
| silly | TRACE |

We can define a function to do the mapping and then do something like this.

`snowflake.configure({ logLevel: toSnowflakeLogLevel(config.logLevel), additionalLogToConsole: false })`

2025-05-02 23:54 UTC, EdwOK commented on snowflake.js
> +    snowflake.configure({ logLevel: 'ERROR', additionalLogToConsole: false })
Done, this was actually my initial suggestion, but it's all good. I think we're aligned now. 
Let me know if there's anything else.

2025-05-06 12:23 UTC, sdewitt-newrelic requested changes

2025-05-06 12:23 UTC, sdewitt-newrelic commented on snowflake.js
> +    return logLevelMapping[winstonLogLevel] || 'OFF';
@EdwOK because this is coming from a config file and is specified by the user, we can't count on it to be in the right case.  It could be `eRRoR` or `httP`.  It also could be `null` as we've seen before.  In other words, it's user input that needs to be scrubbed.  Also, there is no need to declare the `const` array in the function each time it's executed so I suggest it be a global constant.  I suggest doing something like this.

```javascript
const LOG_LEVEL_MAPPING = { ... }

function toSnowflakeLogLevel(winstonLogLevel) {
  if (!winstonLogLevel) {
    return 'OFF'
  }

  return LOG_LEVEL_MAPPING[winstonLogLevel.trim().toLowerCase()] || 'OFF'
}
```

2025-05-08 20:58 UTC, EdwOK commented on snowflake.js
> +    return logLevelMapping[winstonLogLevel] || 'OFF';
done

2025-05-12 13:40 UTC, sdewitt-newrelic approved these changes
LGTM

2025-05-12 13:40 UTC, merged